name: Build

on:
  push:
    branches: [ "master", "v1.*-dev" ]
  pull_request:
    branches: [ "master", "v1.*-dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.19.0, 20.x, 22.x, 24.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: |
        yarn

    - name: Check lint
      run: |
        yarn lint

    - name: Generate GRPC client
      run: |
        yarn build:grpc

    - name: Build with Webpack
      run: |
        yarn build

  test_npm:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.12.0, 20.x, 22.x, 24.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: |
        npm install

    - name: Generate GRPC client
      run: |
        npm run build:grpc

    - name: Run tests with npm
      run: |
        npm test

  test_pnpm:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.12.0, 20.x, 22.x, 24.x]

    steps:
    - uses: actions/checkout@v4

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10

#    - name: Use Node.js ${{ matrix.node-version }}
#      uses: actions/setup-node@v4
#      with:
#        node-version: ${{ matrix.node-version }}
#        cache: "pnpm"

    - name: Install dependencies
      run: |
        pnpm install

    - name: Generate GRPC client
      run: |
        pnpm build:grpc

    - name: Run tests with npm
      run: |
        pnpm test
